### PR TITLE
Adding more notes

### PR DESCRIPTION
**Pull request by jlchan**
- adding `methodswith` to the help section
- added Infiltrator.jl for debugging

### CODE REVIEW

**Comment by brenhinkeller** [comment]
May reorganize a bit in future edits, but LGTM 👍

**Comment by jlchan** [comment]
Please feel free to do so!

**Comment by brenhinkeller** [comment]
I keep having to add new sections as things get longer! May eventually have to separate out more beginner / intermediate / advanced advice?

**Comment by jlchan** [comment]
Hah, I noticed it's been growing too!

Beginner/intermediate/advanced sections makes sense (the README almost looks like it's pretty close to this structure, with Performance tips being the advanced section). It might be neat if the "beginner" section still targeted more experienced Matlab users. I feel like a lot of Julia tutorials cover the "beginner" section well, but that it's harder to find good intermediate/advanced notes.

**Pull request merged**
